### ISSUE TITLE
Getting such error <HaltServer 'Worker failed to boot.' 3>

### ISSUE THREAD

**Issue by duckykao** [ijmarshall/robotreviewer3#53]
2023-07-27 02:55:21 [entrypoint.sh] Starting background cleanup task
2023-07-27 02:55:21 [entrypoint.sh] Starting RobotReviewer Web server
2023-07-27 02:55:21 [2023-07-26 18:55:21 +0000] [11] [INFO] Starting gunicorn 21.2.0
2023-07-27 02:55:21 [2023-07-26 18:55:21 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
2023-07-27 02:55:21 [2023-07-26 18:55:21 +0000] [11] [INFO] Using worker: gevent
2023-07-27 02:55:21 [2023-07-26 18:55:21 +0000] [14] [INFO] Booting worker with pid: 14
2023-07-27 02:55:21 [2023-07-26 18:55:21 +0000] [15] [INFO] Booting worker with pid: 15
2023-07-27 02:55:21 [2023-07-26 18:55:21 +0000] [15] [ERROR] Exception in worker process
2023-07-27 02:55:21 Traceback (most recent call last):
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-07-27 02:55:21     worker.init_process()
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
2023-07-27 02:55:21     super().init_process()
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-07-27 02:55:21     self.load_wsgi()
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-07-27 02:55:21     self.wsgi = self.app.wsgi()
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-07-27 02:55:21     self.callable = self.load()
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-07-27 02:55:21     return self.load_wsgiapp()
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-07-27 02:55:21     return util.import_app(self.app_uri)
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/util.py", line 371, in import_app
2023-07-27 02:55:21     mod = importlib.import_module(module)
2023-07-27 02:55:21   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
2023-07-27 02:55:21     return _bootstrap._gcd_import(name[level:], package, level)
2023-07-27 02:55:21   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2023-07-27 02:55:21   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2023-07-27 02:55:21   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2023-07-27 02:55:21   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2023-07-27 02:55:21   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2023-07-27 02:55:21   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-07-27 02:55:21   File "/var/lib/deploy/server.py", line 2, in <module>
2023-07-27 02:55:21     from robotreviewer import config
2023-07-27 02:55:21   File "/var/lib/deploy/robotreviewer/config.py", line 50, in <module>
2023-07-27 02:55:21     export_config(config())
2023-07-27 02:55:21   File "/var/lib/deploy/robotreviewer/config.py", line 44, in config
2023-07-27 02:55:21     return merge_dicts(json_config(), environ_config())
2023-07-27 02:55:21   File "/var/lib/deploy/robotreviewer/config.py", line 23, in json_config
2023-07-27 02:55:21     with open(path) as p:
2023-07-27 02:55:21 FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/deploy/robotreviewer/config.json'
2023-07-27 02:55:21 [2023-07-26 18:55:21 +0000] [15] [INFO] Worker exiting (pid: 15)
2023-07-27 02:55:22 [2023-07-26 18:55:21 +0000] [14] [ERROR] Exception in worker process
2023-07-27 02:55:22 Traceback (most recent call last):
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-07-27 02:55:22     worker.init_process()
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
2023-07-27 02:55:22     super().init_process()
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-07-27 02:55:22     self.load_wsgi()
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-07-27 02:55:22     self.wsgi = self.app.wsgi()
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-07-27 02:55:22     self.callable = self.load()
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-07-27 02:55:22     return self.load_wsgiapp()
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-07-27 02:55:22     return util.import_app(self.app_uri)
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/site-packages/gunicorn/util.py", line 371, in import_app
2023-07-27 02:55:22     mod = importlib.import_module(module)
2023-07-27 02:55:22   File "/var/lib/deploy/miniconda3/envs/robotreviewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
2023-07-27 02:55:22     return _bootstrap._gcd_import(name[level:], package, level)
2023-07-27 02:55:22   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2023-07-27 02:55:22   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2023-07-27 02:55:22   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2023-07-27 02:55:22   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2023-07-27 02:55:22   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2023-07-27 02:55:22   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-07-27 02:55:22   File "/var/lib/deploy/server.py", line 2, in <module>
2023-07-27 02:55:22     from robotreviewer import config
2023-07-27 02:55:22   File "/var/lib/deploy/robotreviewer/config.py", line 50, in <module>
2023-07-27 02:55:22     export_config(config())
2023-07-27 02:55:22   File "/var/lib/deploy/robotreviewer/config.py", line 44, in config
2023-07-27 02:55:22     return merge_dicts(json_config(), environ_config())
2023-07-27 02:55:22   File "/var/lib/deploy/robotreviewer/config.py", line 23, in json_config
2023-07-27 02:55:22     with open(path) as p:
2023-07-27 02:55:22 FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/deploy/robotreviewer/config.json'
2023-07-27 02:55:22 [2023-07-26 18:55:22 +0000] [14] [INFO] Worker exiting (pid: 14)
2023-07-27 02:55:22 [2023-07-26 18:55:22 +0000] [11] [ERROR] Worker (pid:15) exited with code 3
2023-07-27 02:55:22 [2023-07-26 18:55:22 +0000] [11] [ERROR] Worker (pid:14) was sent SIGTERM!
2023-07-27 02:55:22 [2023-07-26 18:55:22 +0000] [11] [ERROR] Shutting down: Master
2023-07-27 02:55:22 [2023-07-26 18:55:22 +0000] [11] [ERROR] Reason: Worker failed to boot.

**Comment by duckykao** [comment]
Issue Found .... Should create config.json in "\robotreviewer\robotreviewer\config.json" instead of "\robotreviewer\config.json"
